# Generated by Django 4.2.1 on 2023-05-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Изображение книги'),
        ),
    ]
