# Generated by Django 4.2.1 on 2023-05-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_site', '0003_alter_author_author_image_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение книги'),
        ),
    ]
